#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 12 10:37:45 2021

@author: meg
"""
import sys
import math
import matplotlib.pyplot as plt
import numpy as np
from metromin import metromin
from Contact17x17 import Contactclass17
from Contact17x17Q import Contactclass17Q
import datetime
from scipy.stats import gamma
import scipy as scipy
import pandas as pd
import matplotlib.dates as dates

class MY_COVID(metromin,Contactclass17) :
    def __init__(self,Totpop,I0,Tmax,d,R,Kf,nP,Vdelay,Vorder,Vrate,Vrate2,Vgap):
        self.TotPop =  np.dot(55.98e6/66.27,[3.86,4.15,3.95,3.66,4.15,4.51,4,4.4,4.02,4.4,4.66,4.41,3.76,3.37,3.32,5.7-0.376200,0.418000])
        self.I0 = I0
        self.Tmax = Tmax
        self.asize=Tmax+1
        self.d= d
        self.Rpar = R
        self.Ac=0.4
        self.avred=0.3007
        self.Cf= np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.5975])
        self.Hf = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        self.Hc = np.array([0.0,0.0026,0.00084,0.00042,0.0008,0.0026,0.0040,0.0063,0.012,0.019,0.023,0.040,0.096,0.10,0.24,0.50,0.2])
        self.Kf = np.array([0.00031,0.00003,0.00001,0.000001,0.00001,0.00004,0.00006,0.00013,0.00031,0.0007,0.00116,0.00276,0.00867,0.01215,0.03512,0.09063,0.60*0.2])
        self.Hf=self.Kf/self.Hc
        self.Hf[0]=0
        self.nP=nP
        self.nPad = nP+1
        self.Vdelay=Vdelay
        self.Vorder=Vorder
        self.Vrate=Vrate
        self.Vgap=Vgap
        self.Vrate2=Vrate2
        self.lnP=249
        self.lnPad=250

        
       # self.contact=[[0.16911964,0.09572051,0.055995, 0.00372662,0.00372662],[0.09623008, 0.15657723, 0.07461365, 0.00969354,0.00969354],[0.07703133, 0.10096069, 0.11584768, 0.01817469,0.01817469],[0.02226108, 0.04303201, 0.06305222, 0.06045816,0.06045816],[0.02226108, 0.04303201, 0.06305222, 0.06045816,0.06045816]]
        self.contact=Contactclass17.contactmatrix()
        self.contactQ=Contactclass17Q.contactmatrix()
        self.contactQ[16][16]=0
        self.S=np.zeros((17,self.asize))
 
        self.I=np.zeros((17,self.asize))
        self.R=np.zeros((17,self.asize))
        self.V1=np.zeros((17,self.asize+21))
        self.Vcount=np.zeros((17,self.asize+21))
        self.Vcount2=np.zeros((17,self.asize+21))
        self.V2=np.zeros((16,self.asize+21))
        self.Vac=np.zeros((16,self.asize))
        self.Vac2=np.zeros((16,self.asize))
        
        self.F=np.zeros((17,self.asize))
        self.A=np.zeros((17,self.asize))
        self.H=np.zeros((17,self.asize)) #number of people in hospital
        self.Dh=np.zeros((17,self.asize+self.nPad)) #no. transferrred from infected to hospitalised
        self.DRh=np.zeros((17,self.asize)) #no. of those in hosipital who are moved to recovered
        
        self.Di=np.zeros((17,self.asize+self.nPad))
        self.Da=np.zeros((17,self.asize+self.nPad))
        self.Dr=np.zeros((17,self.asize))
        self.Df=np.zeros((17,self.asize))
        self.DRa=np.zeros((17,self.asize))
        self.CHF=np.zeros((17,self.asize+self.nPad))
        self.t=np.linspace(0,self.Tmax,num=self.Tmax+1)
        
        self.asymp=np.zeros((17,self.asize))
        
        self.lPinf=self.mk_gammalong(self.t,6.5,0.62)
        self.lPinc=self.mk_gammalong(self.t,5.1,0.86) 
        self.lPrinc=self.mk_gammalong(self.t,17.8,0.45) 
        
        self.mildsymprecover=self.mk_gammalong(self.t,11.94,0.48)
        self.symphosp=self.log_normallong(self.t,0.845,5.506)
        self.exphosp=self.evalexphosp()
        
        self.mildfull=self.evalmildfull()
        self.fullhosp=self.evalfullhosp()
        
        self.truPinf=self.truePinf()
        self.mildcase=self.normalpinf()
        self.HPinf=self.evalHPinf()
        self.HPinfIso=self.evalHPinfIso(1,0.95)
        self.averHPinf=self.evalHPinfIso(2,0.6667)
        
        
        self.averPinf=self.evalisoPinf(2,0.666667)
        self.AsPinf=self.asympPinf(0,0)
        
        self.presymp1=self.evalisoPinf(0,1)
        self.asymprec=self.evalasympfull()
        #self.mildfull=np.delete(self.mildfull,-1)
      #  self.mildfull=5*np.mean(self.mildfull.reshape(-1,5),axis=1)
      #  self.mildfull=np.insert(self.mildfull,-1,0)
        self.maskAsPinf=self.shorten(self.asympPinf(0,0)*0.9)
        self.maskHPinfIso=self.shorten(0.9*self.evalHPinfIso(0,1)+self.evalHPinf()*0.05+0.9*(self.evalHPinfIso(1,0.95)-self.evalHPinfIso(0,0.95)))
        self.maskPinfIso=self.shorten(0.9*self.evalisoPinf(0,1)+self.truePinf()*0.05+0.9*(self.evalisoPinf(1,0.95)-self.evalisoPinf(0,0.95)))
        
        plt.plot(self.maskAsPinf)
        plt.plot(self.maskHPinfIso)
        plt.plot(self.maskPinfIso)
        plt.show()
        
        plt.plot(self.maskAsPinf)
        plt.plot(self.shorten(self.asympPinf(0,0)))
        plt.show()
        
        plt.plot(self.maskHPinfIso)
        plt.plot(self.shorten(self.evalHPinfIso(1,0.95)))
        plt.show()
        
        plt.plot(self.shorten(self.evalisoPinf(1,0.95)))
        plt.plot(self.maskPinfIso)
        plt.show()
        
        self.PinfIso=self.evalisoPinf(1,0.95)
        self.lPinf=self.shorten(self.lPinf)
        self.averPinf=self.shorten(self.averPinf)
        self.truPinf=self.shorten(self.truPinf)
        self.lPinc=self.shorten(self.lPinc)
        self.lPrinc=self.shorten(self.lPrinc)
        self.mildfull=self.shorten(self.mildfull)
        self.fullhosp=self.shorten(self.fullhosp)
        self.HPinf=self.shorten(self.HPinf)
        self.HPinfIso=self.shorten(self.HPinfIso)
        self.averHPinf=self.shorten(self.averHPinf)
        self.presymp1=self.shorten(self.presymp1)
        self.PinfIso=self.shorten(self.PinfIso)
        self.AsPinf=self.shorten(self.AsPinf)
        self.mildcase=self.shorten(self.mildcase)
        self.asymprec=self.shorten(self.asymprec)
        
        

        """
        fig, ax = plt.subplots()
        fig.set_size_inches(18.5/2, 10.5/2)
        
        ax.fill_between(self.t[0:51],self.shorten(self.evalisoPinf(0,1)),alpha=0.6,color='red',label="$E_{m}$: $d_{q}=0$, $p_{q}=1$")
        ax.fill_between(self.t[0:51],self.shorten(self.evalisoPinf(1,1)),self.shorten(self.evalisoPinf(2,1)),alpha=0.3,color='blue',label="$E_{m}$: $d_{q}=2$, $p_{q}=1$")
        ax.fill_between(self.t[0:51],self.shorten(self.evalisoPinf(0,1)),self.shorten(self.evalisoPinf(1,1)),alpha=0.6,color='blue',label="$E_{m}$: $d_{q}=1$, $p_{q}=1$")

       # plt.plot(self.shorten(self.evalisoPinf(0,1)),ls='dotted',lw=2,color='black', label="Symptom onset")
        ax.fill_between(self.t[0:51],self.shorten(self.truPinf),alpha=0.2,color='grey',label="Maximum potential infectivity $P_{max}$")
        plt.xlim(0,25)
        plt.ylim(0,0.12)
        plt.xlabel("Days since infection", fontsize=14)
        plt.ylabel("Mean infectivity", fontsize=14)
        plt.legend(fontsize=13)
        plt.show()
        
        fig, ax = plt.subplots()
        fig.set_size_inches(18.5/2, 10.5/2)
        
        ax.fill_between(self.t[0:51],self.shorten(self.evalisoPinf(0,1)),alpha=0.6,color='red',label="$E_{m}$: $d_{q}=0$, $p_{q}=1$")
        ax.fill_between(self.t[0:51],self.shorten(self.evalisoPinf(0,1)),self.shorten(self.evalisoPinf(0,0.9)),alpha=0.6,color='blue',label="$E_{m}$: $d_{q}=0$, $p_{q}=0.9$")
        ax.fill_between(self.t[0:51],self.shorten(self.evalisoPinf(0,0.9)),self.shorten(self.evalisoPinf(0,0.5)),alpha=0.3,color='blue',label="$E_{m}$: $d_{q}=0$, $p_{q}=0.5$")
        #plt.plot(self.shorten(self.evalisoPinf(0,1)),ls='dotted',lw=2,color='red',label="Symptom onset")
        ax.fill_between(self.t[0:51],self.shorten(self.truPinf),alpha=0.2,color='grey',label="Maximum potential infectivity $P_{max}$")
        plt.xlim(0,25)
        plt.ylim(0,0.12)
        plt.xlabel("Days since infection", fontsize=14)
        plt.ylabel("Mean infectivity", fontsize=14)
        plt.legend(fontsize=13)
        plt.title("")
        plt.show()
        """
        
        for i in range(0,self.nPad):
            for j in range(0,17):
                self.Da[5][self.nPad-i]=0.4
                self.Dh[0][self.nPad-i]=0
        
        cum=1-np.cumsum(self.mildfull)
        cum2=1-np.cumsum(self.fullhosp)
 
        for i in range(0,17):
            self.A[i][0]=np.sum(self.Da[i][0:self.nPad]*cum[::-1])
            self.H[i][0]=np.sum(self.Dh[i][0:self.nPad]*cum2[::-1])
        print(self.A[5][0],"BOOOM BOOM READ THIS FUCKER")
        for i in range(0,17):
            self.S[i][0]=self.TotPop[i]-self.I[i][0]-self.H[i][0]

    def mk_gamma(self,t, mu, var_coef):
        """ Create and return a varience distribution
            : param t : range of values
            : param mu : average
            : param var_coef : coefficient of variation (=sigma/mu)
        """
        lambda_p = np.sqrt(1/(mu*var_coef**2)) # lambda=alpha/mu=1/(mu V^2)
        alpha_p = mu*lambda_p 
        Pi = gamma.pdf(t[:self.nPad], alpha_p, 0, 1/lambda_p)
        x=np.linspace(0,50,51)
        Pi=Pi/sum(Pi)

        Pi2=np.roll(Pi,1)
        Pi3=(Pi+Pi2)/2
        return(Pi3)
    def mk_gammalong(self,t, mu, var_coef):
        """ Create and return a varience distribution
            : param t : range of values
            : param mu : average
            : param var_coef : coefficient of variation (=sigma/mu)
        """
        lambda_p = np.sqrt(1/(mu*var_coef**2)) # lambda=alpha/mu=1/(mu V^2)
        alpha_p = mu*lambda_p
        x=np.linspace(0,50,self.lnPad)
        Pi = gamma.pdf(x, alpha_p, 0, 1/lambda_p)
        Pi=Pi/sum(Pi)
        return(Pi)
    
    
    
    def log_normallong(self,t, mu, var_coef):
        """ Create and return a varience distribution
            : param t : range of values
            : param mu : average
            : param var_coef : coefficient of variation (=sigma/mu)
        """
        x=np.linspace(0,50,self.lnPad+2)
        Pi = (scipy.stats.weibull_min.pdf(x,mu,0,var_coef))
        Pi=Pi[1:self.lnPad+1]
       # plt.show()
        print(sum(Pi))
        Pi = Pi/sum(Pi) # normalise
        return(Pi)
       
        
    def evalPrd(self):
        Pr=np.zeros(self.lnPad)
        for d in range(len(Pr)):
            for n in range(0,self.lnP):
                Pr[d] += self.lPinc[n]*self.lPrinc[d-n]
        Pr = Pr/sum(Pr)     # normalise the probability    
        return Pr
    
    def evalPhd(self):
        Phrd=np.zeros(self.lnPad)
        for d in range(len(Phrd)):
            for n in range(0,self.lnP):
                Phrd[d] += self.lPinc[n]*self.Phrinc[d-n]
        Phrd = Phrd/sum(Phrd)     # normalise the probability    
        return Phrd  
        
    def evalmildfull(self):
        Pr=np.zeros(self.lnPad)
        for d in range(len(Pr)):
            for n in range(0,self.lnP):
                Pr[d] += self.lPinc[n]*self.mildsymprecover[d-n]
        Pr = Pr/sum(Pr) # normalise the probability    
        return Pr
    
    def evalasympfull(self):
        Pr=np.zeros(self.lnPad)
        for d in range(len(Pr)):
            for n in range(0,self.lnP):
                Pr[d] += self.lPinc[n]*self.truPinf[d-n]
        Pr = Pr/sum(Pr) # normalise the probability    
        return Pr
    
    
    def evalHPinf(self): #No isolation Hpinf
        cumn=1-np.cumsum(np.roll(self.exphosp,0))
        Phrd=np.zeros(self.lnPad)
        for d in range(len(Phrd)):
            for n in range(0,self.lnP):
                Phrd[d] += self.truPinf[d]*cumn[d]
        Phrd = Phrd/self.lnP
        print(sum(Phrd),"L Hpinf reduction")
        return Phrd
    
    def evalHPinfIso(self,d,p): #variable isolation Hpinf
        cumn=1-np.cumsum(np.roll(self.lPinc,d*5)*p)
        Phrd=np.zeros(self.lnPad)
        for d in range(len(Phrd)):
            for n in range(0,self.lnP):
                Phrd[d] += self.HPinf[d]*cumn[d]
        Phrd = Phrd/self.lnP
        print(sum(Phrd),"L Hpinfiso reduction")
        return Phrd
    
    def normalpinf(self): #normalised mild case = 1
        cumn=1-np.cumsum(np.roll(self.mildfull,0))
        Phrd=np.zeros(self.lnPad)
        for d in range(len(Phrd)):
            for n in range(0,self.lnP):
                Phrd[d] += self.truPinf[d]*cumn[d]
        Phrd = Phrd/self.lnP
        print(sum(Phrd),"noramlpinf reduction")
        return Phrd

    def truePinf(self): #maximum potential infectvity
        cumn=1-np.cumsum(np.roll(self.lPinc,5)*(6/7))
        Phrd=np.zeros(self.lnPad)
        for d in range(len(Phrd)):
            for n in range(0,self.lnP):
                Phrd[d] += self.lPinf[d]/cumn[d]
        Phrd = Phrd/(sum(Phrd))
    #    for d in range(len(Phrd)):
    #        for n in range(0,self.lnP):
       #         Phrd[d] += Phrd[d]*cumn2[d]
       # Phrd = Phrd/(sum(Phrd))
        return Phrd

    def asympPinf(self,d,p): #Asymptomatic infectvity with possible pre-incubation testing
        cumn=1-np.cumsum(np.roll(self.lPinc,d*5)*p)
        Phrd=np.zeros(self.lnPad)
        for d in range(len(Phrd)):
            for n in range(0,self.lnP):
                Phrd[d] += self.truPinf[d]*0.3007
        Phrd = Phrd/self.lnP
        print(sum(Phrd),"L asymp reduction")
        return Phrd
    
    def evalisoPinf(self,d,p): #mild case isolation infectivity
        cumn=1-np.cumsum(np.roll(self.lPinc,5*d)*p)
        Phrd=np.zeros(self.lnPad)
        for d in range(len(Phrd)):
            for n in range(0,self.lnP):
                Phrd[d] += self.truPinf[d]*cumn[d]
        Phrd = Phrd/self.lnP
        print(sum(Phrd),"L pinfiso reduction")
        return Phrd
    
    def evalexphosp(self): #Duration from infection to hospitalisation
        Phrd=np.zeros(self.lnPad)
        for d in range(len(Phrd)):
            for n in range(0,self.lnP):
                Phrd[d] += self.lPinc[n]*self.symphosp[d-n]
        Phrd = Phrd/sum(Phrd)   
        return Phrd
    
    def evalfullhosp(self): #Full hospital duration
        Phrd=np.zeros(self.lnPad)
        for d in range(len(Phrd)):
            for n in range(0,self.lnP):
                Phrd[d] += self.lPinc[n]*self.lPrinc[d-n]
        Phrd = Phrd/sum(Phrd)
        print(sum(Phrd))   
        return Phrd
        
    def shorten(self,func):
        func=5*np.mean(func.reshape(-1,5),axis=1)
        func=np.insert(func,-1,0)
        return func
   
    def my_covid(self):
        SumDi=np.zeros(shape=(17,))
        SumRi=np.zeros(shape=(17,))
        SumRh=np.zeros(shape=(17,))
        SumRa=np.zeros(shape=(17,))
        SumDiA=np.zeros(shape=(17,))
        SumDiH=np.zeros(shape=(17,))
        asymp=np.zeros(shape=(17,))
        for d in range(self.Tmax): 
            totalinfect=np.zeros(shape=(17,))
            asymp=np.zeros(shape=(17,))
            for i in range(0,17):   
                for j in range(0,17):
                    if d<=33:
                        totalinfect[i]+=(self.contact[i][j])*(sum(self.averPinf*self.Di[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d]))+sum(self.averHPinf*self.Dh[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d]))+sum(self.AsPinf*self.Da[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d])))
                        asymp[i]+=(self.contact[i][j])*sum(self.AsPinf*self.Da[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d]))
                    elif d>33 and d<=49+7+7:
                        totalinfect[i]+=(self.contact[i][j])*(sum(self.PinfIso*self.Di[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d]))+sum(self.HPinfIso*self.Dh[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d]))+sum(self.AsPinf*self.Da[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d])))
                        asymp[i]+=(self.contact[i][j])*sum(self.AsPinf*self.Da[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d]))
                    else:
                        totalinfect[i]+=(self.contact[i][j])*(sum(self.maskPinfIso*self.Di[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d]))+sum(self.maskHPinfIso*self.Dh[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d]))+sum(self.maskAsPinf*self.Da[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d])))
                        asymp[i]+=(self.contact[i][j])*sum(self.AsPinf*self.Da[j][self.nPad+d:self.nPad+d-self.nP-1:-1]/(self.TotPop[j]-self.F[j][d]))
                
                SumDi[i]= (1-self.Hc[i]-self.Ac)*totalinfect[i]
                SumDiA[i]= self.Ac*totalinfect[i]
                SumDiH[i]= self.Hc[i]*totalinfect[i]
                
                SumRi[i] =sum(self.mildfull*self.Di[i][self.nPad+d:self.nPad+d-self.nP-1:-1])
                SumRh[i]=sum(self.fullhosp*self.Dh[i][self.nPad+d:self.nPad+d-self.nP-1:-1])
                SumRa[i]=sum(self.mildfull*self.Da[i][self.nPad+d:self.nPad+d-self.nP-1:-1])
               
                self.asymp[i][d]=self.Rpar[d]*self.S[i][d]*asymp[i]
               
                self.Di[i][self.nPad+d]=self.Rpar[d]*self.S[i][d]*(SumDi[i])
                self.Dh[i][self.nPad+d]=self.Rpar[d]*self.S[i][d]*(SumDiH[i])
                self.Da[i][self.nPad+d]=self.Rpar[d]*self.S[i][d]*(SumDiA[i])

                self.CHF[i][self.nPad+d]=(self.Cf[i])*SumRi[i]
                
                self.Df[i][d]=self.Hf[i]*SumRh[i]+self.Cf[i]*SumRi[i]
                #+sum(self.CareHF*self.CHF[i][self.nPad+d:self.nPad+d-self.nP-1:-1])
                self.Dr[i][d]=SumRi[i]*(1-self.Cf[i])
                self.DRh[i][d]=(1-self.Hf[i])*SumRh[i]
                self.DRa[i][d]=SumRa[i]
                
                self.S[i][d+1]=self.S[i][d]-self.Di[i][self.nPad+d]-self.Dh[i][self.nPad+d]
                self.I[i][d+1]=self.Di[i][self.nPad+d]-self.Dr[i][d]+self.I[i][d]
                self.R[i][d+1]=self.R[i][d]+self.Dr[i][d]+self.DRh[i][d]
                self.F[i][d+1]=self.F[i][d]+self.Df[i][d]
                self.H[i][d+1]=self.H[i][d]-self.Df[i][d]+self.Dh[i][self.nPad+d]-self.DRh[i][d]+self.Cf[i]*SumRi[i]
                self.A[i][d+1]=self.A[i][d]+self.Da[i][self.nPad+d]-self.DRa[i][d]

            
        #        print(self.H[0][i]+self.F[0][i]+self.R[0][i]+self.S[0][i])
        #print(d,"sumcontact",sumcontact)
        



           
#        plt.semilogy(*self.larger_than(self.t,self.I),'r',label='I')
 #       plt.semilogy(*self.larger_than(self.t,self.R),'g', label='R')
 #       plt.semilogy(*self.larger_than(self.t,self.F),'k',label='F')
 #       plt.semilogy(*self.larger_than(self.t,self.Di[nP+1:]),'b',label='Di')
  #      plt.xlabel("t")
  #      plt.ylabel("P")
  #      plt.legend()
  #      plt.show()
  
    def Rweek(self,weekR):
        emptyR=[]
        for i in range(0,len(weekR)):
            n=0
            while n<7:
                emptyR.append(weekR[i])
                n=n+1
        return emptyR
   
             
       
deaths=[90,125,128,110,123,134,155,168,135,126,163,186,217,196,213,201,196,220,223,238,268]
deaths=[818,844,878,858,896,958,955,944,1000,1075,999,895,917,907,840,807,769,660,591,506,436,398,362,303,237,186,164,130,109,74,68,52,47,32,22,16,13,8,3,5,3,0,0,3,0,2,1]

fatal=pd.read_excel('hospdata.xlsx',sheet_name='Deathage',names=['a','b','a1','b2','a3','b4','a5','b6','a7','b8','a9','b12','b61','a71','14','group15','care'])

deaths=fatal['a']+fatal['b']+fatal['a1']+fatal['b2']+fatal['a3']+fatal['b4']+fatal['a5']+fatal['b6']+fatal['a7']+fatal['b8']+fatal['a9']+fatal['b12']+fatal['b61']+fatal['a71']+fatal['14']+fatal['group15']


TotPop=np.array([3451560,3556732,3823503,3957013,3903430,3752013,4166962,4692543,4651991,3986480,3612537,3900381,3125098,2704065-10000,2337939-10000,4587765-340000,360000])
I0 = np.full(shape=(17,),fill_value=1)
Tmax = 145
asize=Tmax+1
d= 14
Kf = 0
nP=50
Vdelay=10
Vorder=[16,15,14,13,12,11,10,9,8]
Vrate=33
Vrate2=47
Vgap=21
weekR=np.concatenate((np.full(shape=(33,),fill_value=(4.45/0.44784)),np.full(shape=(16,),fill_value=3.6/0.31148),np.full(shape=(5,),fill_value=1.10/0.31148),np.full(shape=(120,),fill_value=0.81/0.31148)))*0.965
weekRearly=np.concatenate((np.full(shape=(33,),fill_value=(4.3/0.42917)),np.full(shape=(7,),fill_value=(3.65/0.3114)),np.full(shape=(16-7-7,),fill_value=3.65/0.3134511511),np.full(shape=(5,),fill_value=1.03/0.315469),np.full(shape=(130,),fill_value=0.81/0.315469)))
weekRlate=np.concatenate((np.full(shape=(33,),fill_value=(4.45/0.42917)),np.full(shape=(7,),fill_value=(4.45/0.42917)),np.full(shape=(16,),fill_value=3.65/0.3134511511),np.full(shape=(5,),fill_value=1.03/0.315469),np.full(shape=(130,),fill_value=0.81/0.315469)))
weekRhigh=weekR*1.1
weekRlow=weekR*0.9


blupalette=["#1659C6",'#1C6FF8','#27BBE0','#31DB92','#1BF118','#9BFA24','#FEF720']

infectpal=['#F4BB00','#FEDE3A','#FEF247','FFFCA1']
deadpal=['#FF4D50','#EE1B10','#C6230F','#AD1F0A']
recoverpal=['#D6FA8C','#BEED53','#A5D721','#82B300']
suspal=['#00B9D3','#57C7DB','#90D6E2','#B8E3EA']

from matplotlib.colors import DivergingNorm
trueweekR=np.concatenate((np.full(shape=(33,),fill_value=(4.45)),np.full(shape=(16,),fill_value=3.65),np.full(shape=(5,),fill_value=1.03),np.full(shape=(120,),fill_value=0.81)))
C19 = MY_COVID(TotPop,I0,Tmax,d,weekR,Kf,nP,Vdelay,Vorder,Vrate,Vrate2,Vgap)
C19.Rweek(weekR)
C19.my_covid()
"""
fig, ax = plt.subplots()
fig.set_size_inches(18.5/2, 10.5/2)

im=ax.plot(C19.t,trueweekR[0:146],color='black',ls="dashed",label="$R_{1}$ value")
plt.axvline(33,color='r',label='02/03: First UK death')
plt.axvline(47,color='yellow',label="16/03: Lockdown Announced, partial measures")
plt.axvline(49,color='orange',label="18/03: Peak daily infections")
plt.axvline(54,color='green',label="23/03: Official Lockdown starts")
plt.axvline(70,color='blue',label="08/04: Peak daily deaths")
plt.xlim(0,145)
plt.xlabel("Day of the simulation")
plt.ylabel("$R_{1}$")
plt.title("$R_{1}$ of the model")
plt.legend(title='Key dates',bbox_to_anchor=(0,0,0.5,-0.15))

plt.show()

#print(C19.contact)
plt.plot(C19.t[0:145], np.sum(C19.asymp,axis=0)[0:145])
plt.plot(C19.t[0:145], )
plt.title("please love me")
plt.show()

plt.plot(C19.t[0:145], np.sum(C19.asymp,axis=0)[0:145]/(np.sum(C19.Di,axis=0)[51:51+145]+np.sum(C19.Dh,axis=0)[51:51+145]+np.sum(C19.Da,axis=0)[51:51+145]))
plt.show()
print(sum(np.sum(C19.asymp,axis=0)[0:145]),"number of asymp inf")
print(sum((np.sum(C19.Di,axis=0)[51:51+145]+np.sum(C19.Dh,axis=0)[51:51+145]+np.sum(C19.Da,axis=0)[51:51+145])),"number of all together inf")
print(sum(np.sum(C19.asymp,axis=0)[0:145])/sum((np.sum(C19.Di,axis=0)[51:51+145]+np.sum(C19.Dh,axis=0)[51:51+145]+np.sum(C19.Da,axis=0)[51:51+145])),"fractionnumber of asymp inf")
matrixx=C19.contact
#fig, ax = plt.subplots()
#im = ax.imshow(matrixx, cmap='cividis', interpolation='none')
#fig.colorbar(im)
#plt.show()
"""
peakdath1 = pd.read_excel('peakdeath.xlsx',sheet_name='peakdeath',names=["death","cumdeath"])
fat=peakdath1['death']
"""

agedeath= pd.read_excel('hospdata.xlsx',sheet_name='newagedeaths',names=["g1","g2","g3","g4","g5","g6","g7"])

agedeath1=agedeath[::-1]
nill=np.zeros((33))

under301=+agedeath1['g2'][0:146]+agedeath1['g3'][0:146]+agedeath1['g4'][0:146]+agedeath1['g5'][0:146]+agedeath1['g6'][0:146]
forty1=agedeath1['g8'][0:146]+agedeath1['g7'][0:146]
fifty1=agedeath1['g10'][0:146]+agedeath1['g9'][0:146]
sixty1=agedeath1['g12'][0:146]+agedeath1['g11'][0:146]
seventy1=agedeath1['g14'][0:146]+agedeath1['g13'][0:146]+agedeath1['g15'][0:146]
eighty1=agedeath1['g16'][0:146]


under50=agedeath1['g1'][0:146]+agedeath1['g2'][0:146]+agedeath1['g3'][0:146]+agedeath1['g4'][0:146]
sixites=agedeath1['g5'][0:146]
seventy=agedeath1['g6'][0:146]
severtyplus=agedeath1['g7'][0:146]


print("deathsaveme",sum(under50))
under501=np.concatenate((nill,under50))

sixites1=np.concatenate((nill,sixites))
seventy1=np.concatenate((nill,seventy))
severtyplus1=np.concatenate((nill,severtyplus))

newdeath2=np.sum(agedeath1,axis=1)[0:146]
newdeath3=np.concatenate((nill,newdeath2))

fig, ax = plt.subplots()
fig.set_size_inches(18.5/2, 10.5/2)

im=ax.stackplot(C19.t,under501[0:146],sixites1[0:146],seventy1[0:146],severtyplus1[0:146],labels=['[0-50]','[50-60]','[60-70]','[70-75]','[75+]'],alpha=0.4,colors=blupalette)
ax.plot(C19.t,newdeath3[0:146],'.',color='orange',label="Daily deaths data")
ax.plot(C19.t,under501[0:146]+sixites1[0:146],'.',color='orange')
ax.plot(C19.t,under501[0:146]+sixites1[0:146]+seventy1[0:146],'.',color='orange')
ax.plot(C19.t,under501[0:146],'.',color='orange')
#ax.plot(np.sum(C19.Df,axis=0)[0:146],color='blue',ls='dotted',label="Model daily deaths")
#ax.plot(np.sum(C19.Df,axis=0)[0:146]-(C19.Df[15])[0:146],color='blue',ls='dotted')
ax.plot(np.sum(C19.Df[0:16],axis=0)[0:146]+C19.Df[16][0:146],color='blue',ls='dotted')
ax.plot(np.sum(C19.Df[0:15],axis=0)[0:146]+0.1*np.sum(C19.Df[0:17],axis=0)[0:146],color='blue',ls='dotted')
ax.plot(np.sum(C19.Df[0:14],axis=0)[0:146]+0.05*np.sum(C19.Df[0:17],axis=0)[0:146],color='blue',ls='dotted')
ax.plot(np.sum(C19.Df[0:13],axis=0)[0:146],color='blue',ls='dotted')

plt.legend(title="Key")
plt.xlabel("Day of the simulation")
plt.ylabel("Number of daily deaths")
plt.title("Daily deaths by age interval")
plt.xlim(30,144)

plt.show()


C23 = MY_COVID(TotPop,I0,Tmax,d,weekR,Kf,nP,Vdelay,Vorder,Vrate,Vrate2,Vgap)
C23.my_covid()
"773	654 1109	1238	2535	3518	25694"

"""
newfat=fat[::-1]

newfat2=newfat.values
nill=np.zeros((33))
print(newfat2)
newfat3=np.concatenate((nill,newfat2))
print(newfat3)
"""
#print(newfat3[47],"BOOP")
#print(newfat3[33],"BEEP")
#plt.plot(np.sum(C19.I,axis=0)+np.sum(C19.A,axis=0),'g',label='Infected')

#plt.plot(np.sum(C19.H,axis=0),'r',label='death')
#plt.plot(np.sum(C19.A,axis=0),'c',label='death')
#plt.show()


#plt.plot(np.sum(C19.Di,axis=0)+np.sum(C19.Dh,axis=0)+np.sum(C19.Da,axis=0))
#plt.title("peak daily infections")
#plt.show()


#plt.plot(np.sum(C19.Di,axis=0)+np.sum(C19.Dh,axis=0)+np.sum(C19.Da,axis=0))
#plt.plot(C19.Di[5]+C19.Dh[5]+C19.Da[5])
#plt.plot(C19.Di[16]+C19.Dh[16]+C19.Da[16])
#plt.title("peak daily infections")
#plt.show()


plt.plot(np.sum(C19.I,axis=0)+np.sum(C19.A,axis=0),'g',label='Infected')

plt.plot(np.sum(C19.H,axis=0),'r',label='death')
plt.plot(np.sum(C19.A,axis=0),'c',label='death')
plt.show()
plt.plot(np.sum(C19.Di,axis=0)+np.sum(C19.Dh,axis=0)+np.sum(C19.Da,axis=0))
plt.plot(C19.Di[5]+C19.Dh[5]+C19.Da[5])
plt.plot(C19.Di[16]+C19.Dh[16]+C19.Da[16])
plt.title("peak daily infections")
plt.show()
plt.plot(np.sum(C19.Df,axis=0))
plt.plot(C19.Df[14])
plt.plot(C19.Df[15])
plt.plot(C19.Df[16])
plt.title("peak deaths infections")
plt.show()



#plt.plot(C19.F[15])
#plt.plot(C19.I[15]+C19.H[15]+C19.A[15])
#plt.plot(C19.H[15])
#plt.title("Di,Dh")
#plt.show()

#plt.plot(C19.Di[16][50:])
#plt.plot(C19.CHF[16][50:])
#plt.plot(C19.Df[16])
#plt.plot()
#plt.title("CHF,Df")
#plt.show()

#plt.plot(C19.Di[5][50:])
#plt.plot(C19.Df[5])
#plt.plot()
#plt.title("CHF,Df")
#plt.show()


#plt.plot(C19.t,np.sum(C19.Dh,axis=0)[51:])
#plt.plot(np.sum(C19.CHF,axis=0))
#plt.show()


#p=deaths[116:317]
#q=p[::-1]
#nill=np.zeros((37))
#r=np.concatenate((nill,q))
#plt.plot(np.sum(C19.Df,axis=0),'g',label='Infected')
#plt.plot(C19.t,newfat3[0:146])
#plt.show()


#plt.plot(np.sum(C19.Df,axis=0),'b',label='death')
#plt.plot(newfat3[0:146],'.',color='r')
#plt.show()
#print("PEAKDEATH,DF",max(np.sum(C19.Df,axis=0)),np.sum(C19.Df,axis=0)[70:80])
#print("PEAKINFECT,Di",max(np.sum(C19.Di,axis=0)),np.sum(C19.Di,axis=0)[40+51:50+51])
#fatal=np.array(deaths[::-1])
#print(np.cumsum(fatal))
#print(np.zeros((20)))
#print(fatal)
#nill=np.zeros((37))
#newdeath=np.concatenate((nill,fatal))

fig, ax = plt.subplots()
fig.set_size_inches(18.5/2, 10.5/2)


under30=C19.F[0]+C19.F[1]+C19.F[2]+C19.F[3]+C19.F[4]+C19.F[5]
forty=C19.F[6]+C19.F[7]
fifty=C19.F[8]+C19.F[9]
sixty=C19.F[10]+C19.F[11]
seventy=C19.F[12]+C19.F[13]
eighty=C19.F[14]+C19.F[15]
carehome=C19.F[16]
im=ax.stackplot(C19.t,under30,forty,fifty,sixty,seventy,eighty,carehome,labels=['Under 30','30-39','40-49','50-59','60-69','70-79','Carehome'],alpha=0.7,colors=blupalette)
#plt.plot(np.cumsum(newfat3[0:200]),'.',color='r')
ax.plot(np.cumsum(newfat3[0:146]),'.',color='orange')
plt.legend()
plt.xlim(33,144)
plt.show()
"""
fig, ax = plt.subplots()
fig.set_size_inches(18.5/2, 10.5/2)


under30=C19.Df[0]+C19.Df[1]+C19.Df[2]+C19.Df[3]+C19.Df[4]+C19.Df[5]
forty=C19.Df[6]+C19.Df[7]
fifty=C19.Df[8]+C19.Df[9]
sixty=C19.Df[10]+C19.Df[11]
seventy=C19.Df[12]+C19.Df[13]
eighty=C19.Df[14]+C19.Df[15]
carehome=C19.Df[16]
#im=ax.stackplot(C19.t,under30,forty,fifty,sixty,seventy,eighty,carehome,labels=['Under 30','[30-39]','[40-49]','[50-59]','[60-69]','[70-79]','Carehomes'],alpha=0.7,colors=blupalette)
#plt.plot(np.cumsum(newfat3[0:200]),'.',color='r')
plt.plot(np.sum(C19.Df,axis=0))
ax.plot((newfat3[0:146]),'.',color='orange')
plt.legend()
plt.xlabel("Day of simulation")
plt.ylabel("Number of daily deaths")
plt.yscale("log")
plt.title("Modelling daily deaths in England during Covid-19 first wave")
plt.xlim(33,144)
plt.ylim(10)
plt.show()

fig, ax = plt.subplots()
fig.set_size_inches(18.5/2, 10.5/2)


plt.plot(np.sum(C19.Df,axis=0))
ax.plot((newfat3[0:146]),'.',color='orange')
plt.legend()
plt.xlabel("Day of simulation")
plt.ylabel("Number of daily deaths")
plt.title("Modelling daily deaths in England during Covid-19 first wave")
plt.xlim(33,144)
plt.ylim(1)
plt.show()


"""
#i#m = ax.imshow(combined3, norm=DivergingNorm(0), cmap='seismic_r', interpolation='none')
#fig.colorbar(im)
#plt.yticks(np.arange(0, 17, 1.0),labels=['[0,5]','[5,10]','[10,15]','[15,20]','[20,25]','[25,30]','[30,35]','[35,40]','[40,45]','[45,50]','[50,55]','[55,60]','[60,65]','[65,70]','[70,75]','[75+]','Carehomes'])
#plt.xticks(np.arange(0, 17, 1.0),labels=['[0,5]','[5,10]','[10,15]','[15,20]','[20,25]','[25,30]','[30,35]','[35,40]','[40,45]','[45,50]','[50,55]','[55,60]','[60,65]','[65,70]','[70,75]','[75+]','Carehomes'])
#plt.setp(ax.get_xticklabels(), rotation=50, ha="right",rotation_mode="anchor",fontsize=11)

#plt.show()

C19 = MY_COVID(TotPop,I0,Tmax,d,weekRhigh,Kf,nP,Vdelay,Vorder,Vrate,Vrate2,Vgap)
C19.my_covid()
highR=np.sum(C19.Df,axis=0)
highRinf=np.sum(C19.Di,axis=0)+np.sum(C19.Da,axis=0)+np.sum(C19.Dh,axis=0)
C20 = MY_COVID(TotPop,I0,Tmax,d,weekRlow,Kf,nP,Vdelay,Vorder,Vrate,Vrate2,Vgap)
C20.my_covid()
lowR=np.sum(C20.Df,axis=0)
lowRinf=np.sum(C20.Di,axis=0)+np.sum(C20.Da,axis=0)+np.sum(C20.Dh,axis=0)

C21 = MY_COVID(TotPop,I0,Tmax,d,weekR,Kf,nP,Vdelay,Vorder,Vrate,Vrate2,Vgap)
C21.my_covid()

midR=np.sum(C21.Df,axis=0)
midRinf=np.sum(C21.Di,axis=0)+np.sum(C21.Da,axis=0)+np.sum(C21.Dh,axis=0)

fig, ax = plt.subplots()
fig.set_size_inches(18.5/2, 10.5/2)
im=ax.plot(midR[0:146],zorder=7,ls="dotted",label="Modelled daily deaths")
ax.fill_between(C19.t,midR[0:146],highR[0:146],alpha=0.1,color='blue',zorder=0)
ax.fill_between(C19.t,lowR[0:146],midR[0:146],alpha=0.1,color='blue',zorder=0)
plt.plot(newfat3[0:146],'.',zorder=3,label="Daily death data")
plt.axvline(33,color='red')#,label='02/03: First UK death')
plt.axvline(47,color='yellow')#,label="16/03: Lockdown Announced, partial measures introduced")
plt.axvline(49,color='orange')#,label="18/03: Peak daily infections")
plt.axvline(54,color='green')#,label="23/03: Official Lockdown starts")
plt.axvline(70,color='blue')#,label="08/04: Peak daily deaths")
plt.xlim(20,144)
plt.ylim(1,3000)
plt.yscale("log")
plt.xlabel("Day of simulation")
plt.ylabel("Log-scale number of daily deaths")
plt.title("Modelling daily deaths in England during Covid-19 first wave")
plt.legend(loc="lower right")
#plt.legend(title="Key dates",bbox_to_anchor=(0,0,0.5,-0.15))
plt.show()

fig, ax = plt.subplots()
fig.set_size_inches(18.5/2, 10.5/2)

ax.fill_between(C19.t,midR[0:146],highR[0:146],alpha=0.2,color='blue',zorder=0)
ax.fill_between(C19.t,lowR[0:146],midR[0:146],alpha=0.1,color='blue',zorder=0)
im=ax.plot(midR[0:146],ls="dotted",zorder=5)
plt.plot(newfat3[0:146],'.',zorder=3)
plt.axvline(33,color='r',label='02/03: First UK death')
plt.axvline(47,color='yellow',label="16/03: Lockdown Announced, partial measures introduced")
plt.axvline(49,color='orange',label="18/03: Peak daily infections")
plt.axvline(54,color='green',label="23/03: Official Lockdown starts")
plt.axvline(70,color='blue',label="08/04: Peak daily deaths")
plt.xlim(20,144)
plt.xlabel("Day of simulation")
plt.ylabel("Daily deaths")
plt.title("Modelling daily deaths in England during Covid-19 first wave")
#plt.legend(title="Key dates",bbox_to_anchor=(0,0,0.7,-0.15))
plt.show()



C19 = MY_COVID(TotPop,I0,Tmax,d,weekRlate,Kf,nP,Vdelay,Vorder,Vrate,Vrate2,Vgap)
C19.my_covid()
highR=np.sum(C19.Df,axis=0)
print("FUCKIN READ LATE LOCKDEATHS",sum(highR))
highRinf=np.array(np.sum(C19.Di,axis=0)+np.sum(C19.Da,axis=0)+np.sum(C19.Dh,axis=0))[51:51+146]
C20 = MY_COVID(TotPop,I0,Tmax,d,weekRearly,Kf,nP,Vdelay,Vorder,Vrate,Vrate2,Vgap)
C20.my_covid()
lowR=np.sum(C20.Df,axis=0)
lowRinf=np.array(np.sum(C20.Di,axis=0)+np.sum(C20.Da,axis=0)+np.sum(C20.Dh,axis=0))[51:51+146]
print("FUCKIN READ EARLY LOCKDEATHS",sum(lowR))
C21 = MY_COVID(TotPop,I0,Tmax,d,weekR,Kf,nP,Vdelay,Vorder,Vrate,Vrate2,Vgap)
C21.my_covid()
midR=np.sum(C21.Df,axis=0)
midRinf=np.array(np.sum(C21.Di,axis=0)+np.sum(C21.Da,axis=0)+np.sum(C21.Dh,axis=0))[51:51+146]
print("FUCKIN LOCKDEATHS",sum(midR))
fig, ax = plt.subplots()
fig.set_size_inches(18.5/2, 10.5/2)

ax.fill_between(C19.t,midR[0:146],highR[0:146],alpha=0.1,color='red',zorder=0)
ax.fill_between(C19.t,lowR[0:146],midR[0:146],alpha=0.1,color='green',zorder=0)
ax.plot(lowR[0:146],color='green',ls="dotted",label="Model deaths: 09/03 early Lockdown")
im=ax.plot(midR[0:146],color='blue',ls="dotted",label="Model deaths: 16/03 Lockdown",zorder=5)
ax.plot(highR[0:146],color='red',ls="dotted",label="Model deaths: 23/03 late Lockdown")

plt.plot(newfat3[0:146],'.',color='orange',label="Daily deaths data",zorder=3)
plt.axvline(47-7,color='green',label="09/03: Lockdown Announced 1 week earlier")
plt.axvline(47,color='blue',label="16/03: Lockdown Announced")
plt.axvline(47+7,color='red',label="23/03: Lockdown Announced 1 week later")
plt.xlim(20,144)
plt.ylim(1)
plt.xlabel("Day of simulation")
plt.ylabel("Log-scale daily deaths")
plt.title("Modelling potential daily deaths with varying dates of Lockdown")
plt.legend(bbox_to_anchor=(0,0,0.5,-0.15))
plt.show()

fig, ax = plt.subplots()
fig.set_size_inches(18.5/2, 10.5/2)

ax.fill_between(C19.t,midRinf[0:146],highRinf[0:146],alpha=0.2,color='red',zorder=0)
ax.fill_between(C19.t,lowRinf[0:146],midRinf[0:146],alpha=0.2,color='green',zorder=0)
ax.plot(lowRinf[0:146],color='green',ls="dotted",label="Model deaths: 09/03 early Lockdown")
im=ax.plot(midRinf[0:146],color='blue',ls="dotted",label="Model deaths: 16/03 Lockdown",zorder=5)
ax.plot(highRinf[0:146],color='red',ls="dotted",label="Model deaths: 23/03 late Lockdown")
plt.axvline(47-7,color='green',label="09/03: Lockdown Announced 1 week earlier")
plt.axvline(47,color='blue',label="16/03: Lockdown Announced")
plt.axvline(47+7,color='red',label="23/03: Lockdown Announced 1 week later")
plt.xlim(20,100)
plt.ylim(100,500000)
plt.yscale("log")
plt.xlabel("Day of simulation")
plt.ylabel("Log-scale daily infections")
plt.title("Modelling potential daily infections with varying dates of Lockdown")
plt.legend(bbox_to_anchor=(0,0,0.5,-0.15))
plt.show()

fig, ax = plt.subplots()
fig.set_size_inches(18.5/2, 10.5/2)

ax.fill_between(C19.t,midRinf[0:146],highRinf[0:146],alpha=0.2,color='red',zorder=0)
ax.fill_between(C19.t,lowRinf[0:146],midRinf[0:146],alpha=0.2,color='green',zorder=0)
ax.plot(lowRinf[0:146],color='green',ls="dotted",label="Model deaths: 09/03 early Lockdown")
im=ax.plot(midRinf[0:146],color='blue',ls="dotted",label="Model deaths: 16/03 Lockdown",zorder=5)
ax.plot(highRinf[0:146],color='red',ls="dotted",label="Model deaths: 23/03 late Lockdown")
plt.axvline(47-7,color='green',label="09/03: Lockdown Announced 1 week earlier")
plt.axvline(47,color='blue',label="16/03: Lockdown Announced")
plt.axvline(47+7,color='red',label="23/03: Lockdown Announced 1 week later")
plt.xlim(20,100)
plt.ylim(100,500000)
plt.xlabel("Day of simulation")
plt.ylabel("Log-scale daily infections")
plt.title("Modelling potential daily infections with varying dates of Lockdown")
plt.legend(bbox_to_anchor=(0,0,0.5,-0.15))
plt.show()



under30=C19.Di[0]+C19.Di[1]+C19.Di[2]+C19.Di[3]+C19.Di[4]+C19.Di[5]+C19.Di[0]
forty=C19.Di[6]+C19.Di[7]
fifty=C19.Di[8]+C19.Di[9]
sixty=C19.Di[10]+C19.Di[11]
seventy=C19.Di[12]+C19.Di[13]
eighty=C19.Di[14]+C19.Di[15]
carehome=C19.Di[16]
plt.stackplot(C19.t,under30[51:],forty[51:],fifty[51:],sixty[51:],seventy[51:],eighty[51:],carehome[51:],labels=['Under 30','30-39','40-49','50-59','60-69','70-79','Carehome'],colors=blupalette)
plt.legend()
plt.show()

under30=C19.I[0]+C19.I[1]+C19.I[2]+C19.I[3]+C19.I[4]+C19.I[5]+C19.I[0]
forty=C19.I[6]+C19.I[7]
fifty=C19.I[8]+C19.I[9]
sixty=C19.I[10]+C19.I[11]
seventy=C19.I[12]+C19.I[13]
eighty=C19.I[14]+C19.I[15]
carehome=C19.I[16]
plt.stackplot(C19.t,under30,forty,fifty,sixty,seventy,eighty,carehome,labels=['Under 30','30-39','40-49','50-59','60-69','70-79','Carehome'],colors=blupalette)
plt.legend()
plt.show()

under30=C19.H[0]+C19.H[1]+C19.H[2]+C19.H[3]+C19.H[4]+C19.H[5]+C19.H[0]
forty=C19.H[6]+C19.H[7]
fifty=C19.H[8]+C19.H[9]
sixty=C19.H[10]+C19.H[11]
seventy=C19.H[12]+C19.H[13]
eighty=C19.H[14]+C19.H[15]
carehome=C19.H[16]
plt.stackplot(C19.t,under30,forty,fifty,sixty,seventy,eighty,carehome,labels=['Under 30','30-39','40-49','50-59','60-69','70-79','80+'],colors=blupalette)
plt.legend()
plt.show()

#plt.plot(Pr)
#plt.show()
#print("Sum Pr =",sum(Pr))
#print("Sum Pinf =",sum(Pinf))

print(min(C21.Di[16]),min(C21.Di[16]),min(C21.Da[16]))
print("Total infections:",sum(np.sum(C21.Di,axis=0))+sum(np.sum(C21.Dh,axis=0))+sum(np.sum(C21.Da,axis=0)))
print("Infections By Group:",(np.sum(C21.Di,axis=1)+np.sum(C21.Dh,axis=1)+np.sum(C21.Da,axis=1)))

print("Total Deaths:",sum(np.sum(C21.Df,axis=0)))
print("Deaths By Group:",(np.sum(C21.Df,axis=1)))

print("Total Hosps:",sum(np.sum(C21.Dh,axis=0)))
print("Hosp By Group:",(np.sum(C21.Dh,axis=1)))

print("Hosp Death By Group:",(np.sum(C21.Dh,axis=1)*C21.Hf))

print("Total Care home non-hosp Death:",sum(np.sum(C21.CHF,axis=0)))
print(C21.Hf)

Di=C19.Di
Dr=C19.Dr
Infe=C19.I
sumcon=0
sumcd=0
for i in range(0,17):
    print(i)
    for j in range(0,17):
        sumcon+=(C19.contact[i][j]/(sum(C19.contact[j])))
    print("the sumcontact of group",i,"used to calculate infections created in group",i,"from other groups",sumcon)
    sumcd+=sumcon
    sumcon=0
print(sumcd,"total influence of infections on each group by others")
sumcd2=0
for j in range(0,17):
    print(j)
    for i in range(0,17):
        sumcon+=(C19.contact[i][j]/(sum(C19.contact[j])))
    print("the sumcontact of produced by group",j,"used to calculate infections created by group",j,"in other groups",sumcon)
    sumcd2+=sumcon
    sumcon=0
print(sumcd,"total influence of infections of each group")
    
    
sumc=[0.76418094361674,0.8796718372911431,0.9489493440069919,1.0386007518837457,1.0620359989638846,1.1737508675133215,1.064023438568784,1.1475576586854337,1.0810414900703413,1.0775608625098698,0.9691229540844309,1.0378652205732475,0.676970208388224,0.7861349074384673,0.9857911792890166,0.7361670905538034,0.7361670905538034]

print(C19.I[15])
print(C19.I[14])

print(C19.I[16])
"""
